spring:
  profiles:
    include:
      - domain
      - lib
  servlet.multipart:
    max-file-size:  20MB
    max-request-size:  20MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  main:
    allow-bean-definition-overriding: true

jwt:
  base64EncodedSecret: eyJzdWIiOiJ0b2RheURpbm5lciIsIm5hbWUiOiJEZXZBbm5hIiwiYWRtaW4iOnRydWUsImlhdCI6MTUxNjIzOTAyMn0
  tokenDurationHr: 24
  swaggerTokenDurationHr: 24
  generator.enabled: true

front.url: http://localhost:3000

logging:
  level:
    ROOT: warn
    kr.co.anna: debug
    p6spy: info

--- # develop
spring:
  config:
    activate:
      on-profile: "develop"

logging:
  level:
    root: ERROR
    p6spy: info
    org.hibernate.SQL : ERROR
  pattern:
    console: "[%highlight(%-5level) %d{yyyy-MM-dd HH:mm:ss} ] %msg | %X{userId} |%X{errCode}%n"

